language:
  - node.js
node_js:
  - stable
cache:
  directories: 
   - node_modules
branches:
  - master
notifications:
  email:
    recipients:
      - hincubator@gmail.com
    on_success: change # default: change
    on_failure: always # default: always
install:
  - npm ci
script:
  - npm run test -- --coverage
after_script:
  - COVERALLS_REPO_TOKEN=$coveralls_repo_token npm run coveral
